//Login AuthentiCation
export const LOGIN_AUTHENTICATION_REQUEST = "LOGIN_AUTHENTICATION_REQUEST";
export const LOGIN_AUTHENTICATION_SUCCESS = "LOGIN_AUTHENTICATION_SUCCESS";
export const LOGIN_AUTHENTICATION_FAILED = "LOGIN_AUTHENTICATION_FAILED";


//actions for getting userlist
export const GET_USERLIST_REQUEST = "GET_USERLIST_REQUEST";
export const GET_USERLIST_SUCCESS = "GET_USERLIST_SUCCESS";
export const GET_USERLIST_FAILED = "GET_USERLIST_FAILED";

//actions for getting deleteuser
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

//actions for getting updateuser
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

//actions for getting All Model List
export const ALL_MODEL_LIST_REQUEST = "ALL_MODEL_LIST_REQUEST";
export const ALL_MODEL_LIST_SUCCESS = "ALL_MODEL_LIST_SUCCESS";
export const ALL_MODEL_LIST_FAILED = "ALL_MODEL_LIST_FAILED";



//get Versions By :AssetType/:ModelName
export const GET_MODEL_VERSIONS_REQUEST = "GET_MODEL_VERSIONS_REQUEST";
export const GET_MODEL_VERSIONS_SUCCESS = "GET_MODEL_VERSIONS_SUCCESS";
export const GET_MODEL_VERSIONS_FAILED = "GET_MODEL_VERSIONS_FAILED";

//Delete Version in Model List
export const DELETE_MODEL_VERSION_REQUEST = "DELETE_MODEL_VERSION_REQUEST";
export const DELETE_MODEL_VERSION_SUCCESS = "DELETE_MODEL_VERSION_SUCCESS";
export const DELETE_MODEL_VERSION_FAILED = "DELETE_MODEL_VERSION_FAILED";


//Jagannath Action Types



//Get Asset Model
export const GET_ASSETMODEL_REQUEST = "GET_ASSETMODEL_REQUEST";
export const GET_ASSETMODEL_SUCCESS = " GET_ASSETMODEL_SUCCESS";
export const GET_ASSETMODEL_FAILED = "GET_ASSETMODEL_FAILED";

//Get Asset by Type
export const GET_ASSETBYTYPE_REQUEST = "GET_ASSETBYTYPE_REQUEST";
export const GET_ASSETBYTYPE_SUCCESS = "GET_ASSETBYTYPE_SUCCESS ";
export const GET_ASSETBYTYPE_FAILED = "GET_ASSETBYTYPE_FAILED";

//Get Version Type
export const GET_VERSIONTYPE_REQUEST = "GET_VERSIONTYPE_REQUEST";
export const GET_VERSIONTYPE_SUCCESS = "GET_VERSIONTYPE_SUCCESS ";
export const GET_VERSIONTYPE_FAILED = "GET_VERSIONTYPE_FAILED";

//Get Asset List
export const GET_ASSETLIST_REQUEST = "GET_ASSETLIST_REQUEST";
export const GET_ASSETLIST_SUCCESS = "GET_ASSETLIST_SUCCESS ";
export const GET_ASSETLIST_FAILED = "GET_ASSETLIST_FAILED";



//Create Model Action

export const CREATE_MODEL_REQUEST ="CREATE_MODEL_REQUEST";
export const CREATE_MODEL_SUCCESS ="CREATE_MODEL_SUCCESS";
export const CREATE_MODEL_FAILED ="CREATE_MODEL_FAILED";

//Search User
export const GET_SEARCH_REQUEST = "GET_SEARCH_REQUEST"
export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS"
export const GET_SEARCH_FAILED = "GET_SEARCH_FAILED"

//Get Vender

export const GET_VENDOR_REQUEST = "GET_VENDOR_REQUEST"
export const GET_VENDOR_SUCCESS = "GET_VENDOR_SUCCESS"
export const GET_VENDOR_FAILED = "GET_VENDPR_FAILED"

//Get Location

export const GET_LOCATION_REQUEST = "GET_LOCATION_REQUEST"
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS"
export const GET_LOCATION_FAILED = "GET_LOCATION_FAILED"

//Get Manufacturer Addmodel

export const GET_MANUFACTURER_REQUEST = "GET_MANUFACTURER_REQUEST";
export const GET_MANUFACTURER_SUCCESS = "GET_MANUFACTURER_SUCCESS";
export const GET_MANUFACTURER_FAILED = "GET_MANUFACTURER_FAILED";


//Delete Vender 

//actions for getting deleteuser
export const DELETE_VENDOR_REQUEST = "DELETE_VENDOR_REQUEST";
export const DELETE_VENDOR_SUCCESS = "DELETE_VENDOR_SUCCESS";
export const DELETE_VENDOR_FAILED = "DELETE_VENDOR_FAILED";

//UPDATE User
export const GET_UPDATE_REQUEST = "GET_UPDATE_REQUEST"
export const GET_UPDATE_SUCCESS = "GET_UPDATE_SUCCESS"
export const GET_UPDATE_FAILED = "GET_UPDATE_FAILED"

//Add Asset to User

export const ADD_USERASSET_REQUEST = "ADD_USERASSET_REQUEST"
export const ADD_USERASSET_SUCCESS = "ADD_USERASSET_SUCCESS"
export const ADD_USERASSET_FAILED = "ADD_USERASSET_FAILED"

//Get Asset List
export const GET_AVALABLEASSET_REQUEST = "GET_AVALABLEASSET_REQUEST";
export const GET_AVALABLEASSET_SUCCESS = "GET_AVALABLEASSET_SUCCESS ";
export const GET_AVALABLEASSET_FAILED = "GET_AVALABLEASSET_FAILED";

//actions for  deleteuserasset
export const DELETE_USERASSET_REQUEST = "DELETE_USERASSET_REQUEST";
export const DELETE_USERASSET_SUCCESS = "DELETE_USERASSET_SUCCESS";
export const DELETE_USERASSET_FAILED = "DELETE_USERASSET_FAILED";

// Get Assign Asset By Id
export const GET_ASSIGNASSET_REQUEST = "GET_ASSIGNASSET_REQUEST"
export const GET_ASSIGNASSET_SUCCESS = "GET_ASSIGNASSET_SUCCESS"
export const GET_ASSIGNASSET_FAILED = "GET_ASSIGNASSET_FAILED"




//



//Abitha Add Vendor actions
export const ADD_VENDOR_REQUEST = "ADD_VENDOR_REQUEST";
export const ADD_VENDOR_SUCCESS = "ADD_VENDOR_SUCCESS";
export const ADD_VENDOR_FAILED = "ADD_VENDOR_FAILED";


// create User


//getting createuser
export const CREATEUSER_REQUEST = 'CREATEUSER_REQUEST';
export const CREATEUSER_SUCCESS = 'CREATEUSER_SUCCESS';
export const CREATEUSER_FAILED = 'CREATEUSER_FAILED';

//getting role
export const GET_ROLE_REQUEST = 'GET_ROLE_REQUEST';
export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS';
export const GET_ROLE_FAILED = 'GET_ROLE_FAILED';


//Getting Asset Ownership
export const GET_OWNERSHIP_REQUEST = 'GET_OWNERSHIP_REQUEST';
export const GET_OWNERSHIP_SUCCESS = 'GET_OWNERSHIP_SUCCESS';
export const GET_OWNERSHIP_FAILED = 'GET_OWNERSHIP_FAILED'; 

//Getting Add Asset
export const ADDASSET_REQUEST = 'ADDASSET_REQUEST';
export const ADDASSET_SUCCESS = 'ADDASSET_SUCCESS';
export const ADDASSET_FAILED = 'ADDASSET_FAILED';


//Getting Device Ownership
export const GET_DEVICEOWNERSHIP_REQUEST = "GET_DEVICEOWNERSHIP_REQUEST";
export const GET_DEVICEOWNERSHIP_SUCCESS = "GET_DEVICEOWNERSHIP_SUCCESS";
export const GET_DEVICEOWNERSHIP_FAILED = "GET_DEVICEOWNERSHIP_FAILED";

//asset tracking serial no
export const ASSET_TRACKINGSERIAL_REQUEST = 'ASSET_TRACKINGSERIAL_REQUEST';
export const ASSET_TRACKINGSERIAL_SUCCESS = 'ASSET_TRACKINGSERIAL_SUCCESS';
export const ASSET_TRACKINGSERIAL_FAILED = 'ASSET_TRACKINGSERIAL_FAILED';

//clearing store Deleted Message
export const CLEAR_DELETED_MESSAGE = 'CLEAR_DELETED_MESSAGE';

// is User Idle
export const IS_USER_IDLE = "IS_USER_IDLE";
export const USER_NOT_IDLE = "USER_NOT_IDLE";
 
//Getting Change Password
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';

//Logout AuthentiCation
export const LOGOUT_AUTHENTICATION_REQUEST = "LOGOUT_AUTHENTICATION_REQUEST";
export const LOGOUT_AUTHENTICATION_SUCCESS = "LOGOUT_AUTHENTICATION_SUCCESS";
export const LOGOUT_AUTHENTICATION_FAILED = "LOGOUT_AUTHENTICATION_FAILED";
